name: Update Apps
on:
  schedule:
    - cron: 0 20 * 1 *
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled'
        required: false
        default: false
env:
  TZ: Asia/Shanghai
  TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
  TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}

jobs:
  update:
    runs-on: ubuntu-latest
    steps:

      - name: Delete older workflow runs and artifacts
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: 3
          keep_minimum_runs: 3

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: SSH Private Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Initialization Environment
        run: |
          sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /etc/mysql /usr/local/lib/android /opt/ghc
          sudo -E apt -y update
          sudo -E apt -y install libime-bin wget
          sudo -E apt -y autoremove --purge
          sudo -E apt -y clean

          ## 
          gofile=go1.22.6.linux-amd64.tar.gz
          wget https://go.dev/dl/$gofile
          sudo rm -rf /usr/local/go
          sudo tar -C /usr/local -xzf $gofile
          export PATH=$PATH:/usr/local/go/bin
          go version

      - name: Setup tmate session
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
        uses: mxschmitt/action-tmate@v3

      - name: go run
        run: |
          rm go.*
          go mod init main
          go mod tidy
          go run *.go

      - name: Commit and Push
        run: |
          git config --global user.name 'Automation - ZenQy'
          git config --global user.email 'zenqy.qin@gmail.com'
          git diff-index --quiet HEAD \
          || (git commit -am "Update - Automated Commit" && git push -u origin main || git stash)

