name: Update Apps
on:
  schedule:
    - cron: 0 20 */2 * *
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled'
        required: false
        default: false
env:
  TZ: Asia/Shanghai
  TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
  TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}

jobs:
  update:
    runs-on: ubuntu-latest
    steps:

      - name: Delete older workflow runs and artifacts
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: 3
          keep_minimum_runs: 3

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Initialization Environment
        run: |
          sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /etc/mysql /usr/local/lib/android /opt/ghc
          sudo -E apt-get -y update
          sudo -E apt-get -y install wget
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get -y clean

      - name: Setup tmate session
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
        uses: mxschmitt/action-tmate@v3

      - name: update
        run: |
          wget https://github.com/ZenQy/updater/releases/latest/download/updater_x64
          chmod +x updater_x64
          ./updater_x64
          rm updater_x64

      - name: Commit and Push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git diff-index --quiet HEAD \
          || (git commit -am "Update - Automated Commit" && git push || git stash)
